# Generated by Django 5.0.7 on 2024-09-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phqgadresponse',
            name='gad_total_score',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='phqgadresponse',
            name='phq_total_score',
            field=models.IntegerField(editable=False),
        ),
    ]
